version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: laporsampah
    networks:
      - appnet

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laporsampah
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
